version : 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: ./gradlew build
      - run:
          name: Publish to Artifactory
          command: ./gradlew artifactoryPublish